apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xdemo-go-tekton 
  janus-idp.io/tekton: xdemo-go-tekton
  backstage.io/kubernetes-id: xdemo-go-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xdemo-go-tekton
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml